# 00 PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


In [ ]:
!nvidia-smi

Fri Mar 17 07:40:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P0    29W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Introduction to Tensors

### Torch.tensor()

**Creating tensors**

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                       [[11,12,13],
                        [14,15,16],
                        [17,18,19]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  5]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[1]

tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers` That is the crux of neural networks

Torch random tensors -> https://pytorch.org/docs/stable/generated/torch.rand.html



In [ ]:
# Create a random tensor

random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.5109, 0.1883, 0.3085, 0.0196],
         [0.9983, 0.2502, 0.9815, 0.5546],
         [0.9162, 0.5715, 0.6266, 0.7477]],

        [[0.8860, 0.3495, 0.6189, 0.8713],
         [0.5521, 0.0591, 0.1959, 0.6222],
         [0.9454, 0.0269, 0.9122, 0.1984]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 2, 4)) # height, width, colour channels (R, G, B)
random_image_size_tensor

tensor([[[0.0335, 0.4237, 0.5984, 0.5466],
         [0.9094, 0.4467, 0.1826, 0.6993]],

        [[0.6408, 0.8937, 0.6094, 0.1742],
         [0.7134, 0.7166, 0.6211, 0.2436]],

        [[0.1027, 0.1007, 0.8714, 0.0854],
         [0.0560, 0.3490, 0.7558, 0.4436]]])

In [ ]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 2, 4]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() or better torch.arange() to don't get deprecated message
one_to_ten = torch.arange(start = 1, end = 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

** Note: ** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # what datatype is the tensor (e.g. float 32 or float16 etc.)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32) # long == int 64
int_32_tensor.dtype

torch.int32

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand((3, 4))
some_tensor

tensor([[0.8461, 0.6935, 0.9818, 0.0638],
        [0.2607, 0.1307, 0.0212, 0.0084],
        [0.9001, 0.8098, 0.0517, 0.0089]])

In [ ]:
some_tensor.size, some_tensor.shape, some_tensor.size()

(<function Tensor.size>, torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
# Find out details about some tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8461, 0.6935, 0.9818, 0.0638],
        [0.2607, 0.1307, 0.0212, 0.0084],
        [0.9001, 0.8098, 0.0517, 0.0089]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations) 

Tensor operations include: 
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match(совпадать):
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.1 ms, sys: 783 µs, total: 1.89 ms
Wall time: 2.01 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 34 µs, sys: 5 µs, total: 39 µs
Wall time: 42.9 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8 , 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

In [ ]:
# Matrix multiplication operation works when tensor_A is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.T.shape}, tensor_B.T = {tensor_B.shape}  (same shape as above)")
print(f"Multiplying: {tensor_A.T.shape} @ {tensor_B.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.matmul(tensor_A.T, tensor_B)
print(output)
print(f"\nOutput shape: {output.shape}")

### Finding the min, max, mean, sum etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

In [ ]:
# Find the min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x), x.max()

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
# Find the sum
torch.sum(x), x.sum()

### Finding the positional min and max

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of of each other (vstack) or side by side (hstack)
* Squeeze(сжимать) - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view ot the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]
print(f"Previous shape: {x_original.shape}")

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 999
print(f"x_original[0, 0, 0] = {x_original[0, 0, 0]}")
print(f"x_permuted[0, 0, 0] = {x_permuted[0, 0, 0]}")

x_original[0, 0, 0] = 999.0
x_permuted[0, 0, 0] = 999.0


### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 19).reshape(2, 3, 3)
x, x.shape

In [ ]:
# Let's index on our new tensor
x[0]

In [ ]:
# Let's index on the middle bracket (dim=1)
x[1][0]

In [ ]:
# Let's index on the most inner bracket (last dimesion)
x[0][0][0]

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

In [ ]:
 # Get all values of the 0 diension but only the 1 index value of 1st and 2nd dimension
 x[:, 1, 1]

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

In [ ]:
# Index on x to return 18
print(x)

# Index on x to return 3, 6, 9
x[0, :, 2]

### PyTorch tensors & NumPY
Numpy is a popular scientific Python numerical computing limrary.

And because of this, PyTorch has functionality to iteract with it.
* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

In [ ]:
# Change the value of array, what will this do to `tensor`?
array = array +1
array, tensor

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

### Reproducibility (trying to take random out of random)
In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random sedd does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_A)
print(random_tensor_A == random_tensor_B)

In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

### Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers. thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

# 1 Getting a GPU

1. Easiest = Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [ ]:
!nvidia-smi

## 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch

torch.cuda.is_available()

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

E.g. run on GPU if available, else default to CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

In [ ]:
# Count number of devices
torch.cuda.device_count()

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU relults in faster computations

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor no on GPU
print(tensor, tensor.device)

In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

## 4. Moving tensors back to the CPU

In [ ]:
 # if tensor in on GPU, can't transform it to NumPy
 tensor_on_gpu.numpy()

In [ ]:
## To fix the GPU tensor with NumPy issue, we can first set it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

# Exercises

In [ ]:
import torch

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on 
* torch.Tensor
* torch.cuda.

2. Create a random tensor with shape (7, 7).

In [ ]:
tensor_7x7 = torch.rand(7, 7)
tensor_7x7

tensor([[0.5440, 0.2630, 0.8474, 0.4634, 0.6285, 0.2509, 0.6553],
        [0.3975, 0.8981, 0.7993, 0.6864, 0.5282, 0.1683, 0.3856],
        [0.4468, 0.2092, 0.1018, 0.1547, 0.8602, 0.0983, 0.6359],
        [0.2247, 0.0858, 0.7635, 0.6954, 0.6323, 0.8252, 0.0916],
        [0.0015, 0.3372, 0.8005, 0.5401, 0.5846, 0.2823, 0.7624],
        [0.3979, 0.6819, 0.3241, 0.6321, 0.8967, 0.9073, 0.8102],
        [0.6163, 0.5444, 0.2557, 0.1064, 0.2876, 0.4163, 0.0703]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
tensor_1x7 = torch.rand(size=(1, 7))

print(f"tensor_1x7: {tensor_1x7}\n")
print(f"tensor_1x7.T: {tensor_1x7.T}\n")

print(f"tensor_1X7 @ tensor_7x7: {torch.matmul(tensor_1x7, tensor_7x7)}\n")
print(f"tensor_7x7 @ tensor_1x7.T: {torch.matmul(tensor_7x7, tensor_1x7.T)}\n") # inner dimensions must be equals

tensor_1x7: tensor([[0.4074, 0.0589, 0.7221, 0.5549, 0.9305, 0.3580, 0.8965]])

tensor_1x7.T: tensor([[0.4074],
        [0.0589],
        [0.7221],
        [0.5549],
        [0.9305],
        [0.3580],
        [0.8965]])

tensor_1X7 @ tensor_7x7: tensor([[1.3887, 1.4046, 1.9796, 1.5510, 2.3818, 1.6017, 1.8621]])

tensor_7x7 @ tensor_1x7.T: tensor([[2.3682],
        [2.0703],
        [1.7593],
        [1.9996],
        [2.2267],
        [2.6725],
        [1.0065]])



4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [ ]:
# Set the random seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# 2. Create tensor 7x7
new_tensor_7x7 = torch.rand(size=(7, 7))
print(f"New_tensor_7x7: {new_tensor_7x7}")

# 3. Matrix multiplication
new_tensor_1x7 = torch.rand(size=(1, 7))

print(f"new_tensor_1x7: {new_tensor_1x7}\n")

print(f"new_tensor_1X7 @ new_tensor_7x7: {torch.matmul(new_tensor_1x7, new_tensor_7x7)}\n")
print(f"new_tensor_7x7 @ new_tensor_1x7.T: {torch.matmul(new_tensor_7x7, new_tensor_1x7.T)}\n")

New_tensor_7x7: tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
new_tensor_1x7: tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

new_tensor_1X7 @ new_tensor_7x7: tensor([[2.1581, 1.9307, 2.8454, 2.6230, 1.9117, 2.0266, 1.4257]])

new_tensor_7x7 @ new_tensor_1x7.T: tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])



5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234

In [ ]:
torch.cuda.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [ ]:
torch.manual_seed(1234) # set psedo-generator random numbers

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensor
tensor_a = torch.rand(size=(2, 3), device=device)
tensor_b = torch.rand(size=(2, 3), device=device)

print(f"tensor_a: {tensor_a}")
print(f"tensor_b: {tensor_b}")

Device: cuda
tensor_a: tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor_b: tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).


In [ ]:
# Figure out our tensors
print(f"tensor_a: {tensor_a}")
print(f"tensor_b: {tensor_b}\n")

# Matrix multiplication
tensor_c = torch.matmul(tensor_a, tensor_b.T)

print(f"tensor_a @ tensor_b.T: \n{tensor_c, tensor_c.shape}\n")

tensor_a: tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor_b: tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')

tensor_a @ tensor_b.T: 
(tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0'), torch.Size([2, 2]))



8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Maximum value of the output of 7
print(f"Maximem value tensor_c: {tensor_c.max()}")

# Minimum value of the output of 7
print(f"Minimum value tensor_c: {tensor_c.min()}")

Maximem value tensor_c: 0.7667766809463501
Minimum value tensor_c: 0.27863210439682007


9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Index of maximum value tensor_c
arg_max = torch.argmax(tensor_c)
print(f"Index of maximum: {arg_max}")

# Index of minimum value tensor_c
arg_min = torch.argmin(tensor_c)
print(f"Index of minimum: {arg_min}")

Index of maximum: 1
Index of minimum: 0


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
# Set manual seed 7
torch.manual_seed(7)

# Create random tensor with shape (1, 1, 1, 10)
tensor_bd = torch.rand(size=(1, 1, 1, 10))

# New squeezed tensor from first
tensor_squeezed = torch.squeeze(tensor_bd)

print(f"tensor_bd: \n{tensor_bd, tensor_bd.shape}\n"
      f"tensor_squeezed: \n{tensor_squeezed, tensor_squeezed.shape}")

tensor_bd: 
(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))
tensor_squeezed: 
(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
